# Form implementation generated from reading ui file 'YiYan/YiYanConfig.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_YiYanConfig(object):
    def setupUi(self, YiYanConfig):
        YiYanConfig.setObjectName("YiYanConfig")
        YiYanConfig.resize(400, 145)
        self.verticalLayout = QtWidgets.QVBoxLayout(YiYanConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=YiYanConfig)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ledt_api_secret = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.ledt_api_secret.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ledt_api_secret.setObjectName("ledt_api_secret")
        self.gridLayout_2.addWidget(self.ledt_api_secret, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.ledt_appid = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.ledt_appid.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ledt_appid.setObjectName("ledt_appid")
        self.gridLayout_2.addWidget(self.ledt_appid, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=YiYanConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(YiYanConfig)
        self.buttonBox.accepted.connect(YiYanConfig.accept) # type: ignore
        self.buttonBox.rejected.connect(YiYanConfig.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(YiYanConfig)

    def retranslateUi(self, YiYanConfig):
        _translate = QtCore.QCoreApplication.translate
        YiYanConfig.setWindowTitle(_translate("YiYanConfig", "大模型配置"))
        self.groupBox_3.setTitle(_translate("YiYanConfig", "文心一言大模型"))
        self.label.setText(_translate("YiYanConfig", "appid"))
        self.label_2.setText(_translate("YiYanConfig", "api secret"))
