# Form implementation generated from reading ui file 'UI/Choice.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Choice(object):
    def setupUi(self, Choice):
        Choice.setObjectName("Choice")
        Choice.resize(339, 74)
        self.verticalLayout = QtWidgets.QVBoxLayout(Choice)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_tip = QtWidgets.QLabel(parent=Choice)
        self.lab_tip.setObjectName("lab_tip")
        self.horizontalLayout.addWidget(self.lab_tip)
        self.com_choice = QtWidgets.QComboBox(parent=Choice)
        self.com_choice.setObjectName("com_choice")
        self.horizontalLayout.addWidget(self.com_choice)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Choice)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Choice)
        self.buttonBox.accepted.connect(Choice.accept) # type: ignore
        self.buttonBox.rejected.connect(Choice.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Choice)

    def retranslateUi(self, Choice):
        _translate = QtCore.QCoreApplication.translate
        Choice.setWindowTitle(_translate("Choice", "Dialog"))
        self.lab_tip.setText(_translate("Choice", "TextLabel"))
