# Form implementation generated from reading ui file 'UI/LineInput.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LineInput(object):
    def setupUi(self, LineInput):
        LineInput.setObjectName("LineInput")
        LineInput.resize(428, 72)
        self.verticalLayout = QtWidgets.QVBoxLayout(LineInput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_tip = QtWidgets.QLabel(parent=LineInput)
        self.lab_tip.setObjectName("lab_tip")
        self.horizontalLayout.addWidget(self.lab_tip)
        self.ledt_input = QtWidgets.QLineEdit(parent=LineInput)
        self.ledt_input.setObjectName("ledt_input")
        self.horizontalLayout.addWidget(self.ledt_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=LineInput)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LineInput)
        self.buttonBox.accepted.connect(LineInput.accept) # type: ignore
        self.buttonBox.rejected.connect(LineInput.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LineInput)

    def retranslateUi(self, LineInput):
        _translate = QtCore.QCoreApplication.translate
        LineInput.setWindowTitle(_translate("LineInput", "Dialog"))
        self.lab_tip.setText(_translate("LineInput", "Tip"))
