# Form implementation generated from reading ui file 'UI/PlainTextInput.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlainTextInput(object):
    def setupUi(self, PlainTextInput):
        PlainTextInput.setObjectName("PlainTextInput")
        PlainTextInput.resize(400, 171)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlainTextInput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plain_input = QtWidgets.QPlainTextEdit(parent=PlainTextInput)
        self.plain_input.setObjectName("plain_input")
        self.verticalLayout.addWidget(self.plain_input)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=PlainTextInput)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PlainTextInput)
        self.buttonBox.accepted.connect(PlainTextInput.accept) # type: ignore
        self.buttonBox.rejected.connect(PlainTextInput.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PlainTextInput)

    def retranslateUi(self, PlainTextInput):
        _translate = QtCore.QCoreApplication.translate
        PlainTextInput.setWindowTitle(_translate("PlainTextInput", "Dialog"))
